#spring :
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://ec2-15-164-196-118.ap-northeast-2.compute.amazonaws.com:3306/objeto?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: USER_NAME
#    password: USER_PASSWORD
#  jpa:
#    database : mysql
#    show-sql : false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false