server :
  port: 8080
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store : src/main/resources/keystore/pkcs12_keystore.p12
    key-store-password : 123456
spring :
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://ec2-15-164-196-118.ap-northeast-2.compute.amazonaws.com:3306/objeto?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 1234!
  jpa:
    database : mysql
    show-sql : false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  data:
    redis:
      port: 6379
      host: localhost

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    root : info
    p6spy: trace

#sentry:
#  dsn: "https://aca63734d7b844709390e4b636d2a967@o4505215665897472.ingest.sentry.io/4505215667011584"
#  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
#  # We recommend adjusting this value in production.
#  traces-sample-rate: 1.0
#  enable-tracing : true
#  debug: false

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

