server :
  port: 8080

spring :
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://ec2-15-164-196-118.ap-northeast-2.compute.amazonaws.com:3306/objeto?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: USER_NAME
    password: USER_PASSWORD
  jpa:
    database : mysql
    show-sql : false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  data:
    redis:
      port: 6379
      host: localhost
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat  # yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  profiles:
    active: deploy
decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    root : info
    p6spy: trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

---
spring :
  config :
    activate:
      on-profile: oracle
    import:
      - classpath:/config/oracle-config.yml
---
spring :
  config :
    activate:
      on-profile: mssql
    import:
      - classpath:/config/mysql-config.yml
---
spring :
  config :
    activate:
      on-profile: mysql
    import:
      - classpath:/config/mssql-config.yml

---
spring :
  config :
    activate:
      on-profile: deploy
    import:
      - file:///app/deploy-config.yml